#!/bin/bash
source bash/execute.sh

# usage: ./run npm install express --save

command=$(argsToCommand "$@")
command=$(escapeDoubleQuoates "$command")

execute docker-compose run --user=node -v $PWD:/home/node/app api /bin/bash -c "cd /home/node/app && $command"
